feat: tried fail-fast

diff --git a/.github/workflows/try-fail-fast.yml b/.github/workflows/try-fail-fast.yml
--- a/.github/workflows/try-fail-fast.yml
+++ b/.github/workflows/try-fail-fast.yml
@@ -6,12 +6,39 @@ on:
       - master
 
 jobs:
+  # prepare-dessert:
+  #   runs-on: ubuntu-latest
+  #   # 為了避免無限迴圈，所以job不能依賴自己
+  #   # needs: prepare-dessert
+  #   # if: ${{ needs.prepare-dessert.outputs.result == 'success' }} 
+  #   strategy:
+  #     matrix:
+  #       fruit: [mango, strawberry]
+  #       dessert: ['ice cream', cake]
+  #       include:
+  #         - size: small
+  #         - size: large
+  #           dessert: 'ice cream'
+  #         - fruit: mango
+  #           decoration: chocolate
+  #         - fruit: raspberry
+  #         - fruit: raspberry
+  #           dessert: 'ice cream'
+  #   steps:
+  #     - name: throw error
+  #       if: ${{ matrix.fruit == 'mango'}}
+  #       run: |
+  #         echo "Using exit 1 to test if this can stop next job" 
+  #         exit 1
+  #     - name: The first step of a matrix job
+  #       if: ${{ success() }}
+  #       run: |
+  #         echo "${{ matrix.fruit }} ${{ matrix.dessert }} ${{ matrix.decoration }} ${{ matrix.size }}"
+
   prepare-dessert:
     runs-on: ubuntu-latest
-    # 為了避免無限迴圈，所以job不能依賴自己
-    # needs: prepare-dessert
-    # if: ${{ needs.prepare-dessert.outputs.result == 'success' }} 
     strategy:
+      fail-fast: true
       matrix:
         fruit: [mango, strawberry]
         dessert: ['ice cream', cake]
@@ -28,9 +55,5 @@ jobs:
       - name: throw error
         if: ${{ matrix.fruit == 'mango'}}
         run: |
-          echo "Using exit 1 to test if this can stop next job" 
+          echo "Throw error on purpose" 
           exit 1
-      - name: The first step of a matrix job
-        if: ${{ success() }}
-        run: |
-          echo "${{ matrix.fruit }} ${{ matrix.dessert }} ${{ matrix.decoration }} ${{ matrix.size }}"
