feat: try to use continue-on-error independently

diff --git a/.github/workflows/try-fail-fast.yml b/.github/workflows/try-fail-fast.yml
--- a/.github/workflows/try-fail-fast.yml
+++ b/.github/workflows/try-fail-fast.yml
@@ -32,38 +32,43 @@ jobs:
   #       run: |
   #         echo "${{ matrix.fruit }} ${{ matrix.dessert }} ${{ matrix.decoration }} ${{ matrix.size }}"
 
-  prepare-dessert:
-    runs-on: ubuntu-latest
-    # continue-on-error: false
-    strategy:
-      # fail-fast: true
-      matrix:
-        fruit: [mango, strawberry]
-        dessert: ['ice cream', cake]
-        include:
-          - size: small
-          - size: large
-            dessert: 'ice cream'
-          - fruit: mango
-            decoration: chocolate
-          - fruit: raspberry
-          - fruit: raspberry
-            dessert: 'ice cream'
-    steps:
-      - name: throw error
-        if: ${{ matrix.fruit != 'mango'}}
-        run: |
-          echo "Throw error on purpose" 
-          exit 1
-      - name: print something
-        run: echo ${{ matrix.fruit}} ${{ matrix.dessert}} 
+  # prepare-dessert:
+  #   runs-on: ubuntu-latest
+  #   # continue-on-error: false
+  #   strategy:
+  #     # fail-fast: true
+  #     matrix:
+  #       fruit: [mango, strawberry]
+  #       dessert: ['ice cream', cake]
+  #       include:
+  #         - size: small
+  #         - size: large
+  #           dessert: 'ice cream'
+  #         - fruit: mango
+  #           decoration: chocolate
+  #         - fruit: raspberry
+  #         - fruit: raspberry
+  #           dessert: 'ice cream'
+  #   steps:
+  #     - name: throw error
+  #       if: ${{ matrix.fruit != 'mango'}}
+  #       run: |
+  #         echo "Throw error on purpose" 
+  #         exit 1
+  #     - name: print something
+  #       run: echo ${{ matrix.fruit}} ${{ matrix.dessert}} 
 
   next-job:
     runs-on: ubuntu-latest
-    needs: prepare-dessert
+    continue-on-error: true
+    # needs: prepare-dessert
     # strategy:
     #   fail-fast: true
     steps:
-      - name: print something
+      - name: throw error
         run: |
-          echo Hello
+          echo "Throw error on purpose" 
+          exit 1
+      - name: after throw error
+        run: |
+          echo "This is after throw error"
